CREATE TABLE USERS
(
  USER_ID NUMBER NOT NULL,
  USER_NAME NVARCHAR2(40) NOT NULL,
  USER_PASSWORD NVARCHAR2(60) NOT NULL,
  USER_FULLNAME NVARCHAR2(80),
  USER_CITY NVARCHAR2(40),
  USER_GENDER VARCHAR2(1 CHAR),
  USER_AGE NUMBER,
  USER_STARSIGN NVARCHAR2(10),
  USER_PROFILE_VISITS NUMBER DEFAULT 0 NOT NULL,
  USER_ONLINE VARCHAR2(1) DEFAULT 'N' NOT NULL
, CONSTRAINT USERS_PK PRIMARY KEY
  (
    USER_ID
  )
  ENABLE
)
;

ALTER TABLE USERS
ADD CONSTRAINT USER_NAMES_UK1 UNIQUE
(
  USER_NAME
)
 ENABLE
;

COMMENT ON COLUMN USERS.USER_NAME IS 'Username. Will be used in login.'
;

COMMENT ON COLUMN USERS.USER_PASSWORD IS 'Password. Will be used for authentication.'
;

COMMENT ON COLUMN USERS.USER_GENDER IS 'Proper values are M or F or NULL.'
;

COMMENT ON COLUMN USERS.USER_AGE IS 'Proper ages vary from 18 to 150.'
;

COMMENT ON COLUMN USERS.USER_STARSIGN IS 'User starsign. Valid values are the sign names in Bulgarian or NULL.'
;

COMMENT ON COLUMN USERS.USER_ONLINE IS 'Values are Y and N. Cannot be NULL.'
;
