CREATE TABLE USER_INTERESTS
(
  USER_INTEREST_ID NUMBER NOT NULL,
  USER_ID NUMBER NOT NULL,
  USER_INTEREST CLOB NOT NULL
, CONSTRAINT USER_INTERESTS_PK PRIMARY KEY
  (
    USER_INTEREST_ID
  )
  ENABLE
)
;

ALTER TABLE USER_INTERESTS
ADD CONSTRAINT USER_INTERESTS_USERS_FK1 FOREIGN KEY
(
  USER_ID
)
REFERENCES USERS
(
USER_ID
) ENABLE
;
